
CREATE TABLE  "ZAKLAD" 
   (	"ZAKLAD_ID" NUMBER(10,0), 
	"KUPON_ID" NUMBER(10,0), 
	"WYDARZENIE_ID" NUMBER(10,0), 
	"DATA_ROZPOCZECIA" DATE, 
	"DATA_ZAKONCZENIA" DATE, 
	"STATUS" NUMBER(1,0), 
	 CONSTRAINT "ZAKLAD_PK" PRIMARY KEY ("ZAKLAD_ID") ENABLE
   ) ;ALTER TABLE  "ZAKLAD" ADD CONSTRAINT "ZAKLAD_KUPON_FK" FOREIGN KEY ("KUPON_ID")
	  REFERENCES  "KUPON" ("KUPON_ID") ON DELETE CASCADE ENABLE;ALTER TABLE  "ZAKLAD" ADD CONSTRAINT "ZAKLAD_WYDARZENIE_FK" FOREIGN KEY ("WYDARZENIE_ID")
	  REFERENCES  "WYDARZENIE" ("WYDARZENIE_ID")   ENABLE;

CREATE TABLE  "UZYTKOWNIK" 
   (	"UZYTKOWNIK_ID" NUMBER(10,0), 
	"IMIE" VARCHAR2(15) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(15) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20) NOT NULL ENABLE, 
	"NR_TELEFONU" NUMBER(10,0), 
	 CONSTRAINT "UZYTKOWNIK_PK" PRIMARY KEY ("UZYTKOWNIK_ID") ENABLE
   ) ;


CREATE TABLE  "UPRAWNIENIA" 
   (	"UPRAWNIENIA_ID" NUMBER(5,0), 
	"UZYTKOWNIK" NUMBER(1,0), 
	"ADMINISTRATOR" NUMBER(1,0), 
	 CONSTRAINT "UPRAWNIENIA_PK" PRIMARY KEY ("UPRAWNIENIA_ID") ENABLE
   ) ;


CREATE TABLE  "KUPON" 
   (	"KUPON_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"UZYTKOWNIK_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KURS" FLOAT(126) NOT NULL ENABLE, 
	"POSTAWIONE_SRODKI" FLOAT(126) NOT NULL ENABLE, 
	"WYGRANA" FLOAT(126), 
	"STATUS" NUMBER(1,0), 
	 CONSTRAINT "KUPON_PK" PRIMARY KEY ("KUPON_ID") ENABLE
   ) ;ALTER TABLE  "KUPON" ADD CONSTRAINT "KUPON_UZYTKOWNIK_FK" FOREIGN KEY ("UZYTKOWNIK_ID")
	  REFERENCES  "UZYTKOWNIK" ("UZYTKOWNIK_ID") ON DELETE CASCADE ENABLE;
    
CREATE TABLE  "KONTO" 
   (	"LOGIN" VARCHAR2(20), 
	"UZYTKOWNIK_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"UPRAWNIENIA_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"HASLO" VARCHAR2(20) NOT NULL ENABLE, 
	"SRODKI" FLOAT(126), 
	 CONSTRAINT "KONTO_PK" PRIMARY KEY ("LOGIN") ENABLE
   ) ;ALTER TABLE  "KONTO" ADD CONSTRAINT "KONTO_UPRAWNIENIA_FK" FOREIGN KEY ("UPRAWNIENIA_ID")
	  REFERENCES  "UPRAWNIENIA" ("UPRAWNIENIA_ID") ENABLE;ALTER TABLE  "KONTO" ADD CONSTRAINT "KONTO_UZYTKOWNIK_FK" FOREIGN KEY ("UZYTKOWNIK_ID")
	  REFERENCES  "UZYTKOWNIK" ("UZYTKOWNIK_ID") ON DELETE CASCADE ENABLE;

CREATE TABLE  "DYSCYPLINA" 
   (	"NAZWA" VARCHAR2(20), 
	 CONSTRAINT "DYSCYPLINA_PK" PRIMARY KEY ("NAZWA") ENABLE
   ) ;
   
CREATE TABLE  "WYDARZENIE" 
   (	"WYDARZENIE_ID" NUMBER(10,0), 
	"DYSCYPLINANAZWA" VARCHAR2(20), 
	"DRUZYNA1" VARCHAR2(20), 
	"DRUZYNA2" VARCHAR2(20), 
	"DATA_ROZPOCZECIA" DATE, 
	"DATA_ZAKONCZENIA" DATE, 
	"KURS1" FLOAT(126), 
	"KURS2" FLOAT(126), 
	"KURS3" FLOAT(126), 
	"KTO_WYGRAL" NUMBER(1,0), 
	 CONSTRAINT "WYDARZENIE_PK" PRIMARY KEY ("WYDARZENIE_ID") ENABLE
   ) ;ALTER TABLE  "WYDARZENIE" ADD CONSTRAINT "WYDARZENIE_DYSCYPLINA_FK" FOREIGN KEY ("DYSCYPLINANAZWA")
	  REFERENCES  "DYSCYPLINA" ("NAZWA") ENABLE;


